# Use postgres/example user/password credentials
version: '3.1'

services:

  db_postgres:
    image: postgres
    restart: 'always'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data/
      - ../sql/todo.up.postgres.sql:/docker-entrypoint-initdb.d/todo.up.postgres.sql

volumes:
  postgres-data:

networks:
  postgres:
    driver: bridge
